-- +goose Up

CREATE TABLE USERS (
    id UUID PRIMARY KEY,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL,
    NAME VARCHAR(255) NOT NULL
);

-- +goose Down
DROP TABLE USERS;


